version : "3.7"

services:

  app:
    container_name: app
    build:
      context: .
      target: systemio-image
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/
    depends_on:
      - postgres

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8876:80"
    depends_on:
      - app

  postgres:
      container_name: postgres
      image: postgres:latest
      env_file:
        - ./.env
      environment:
        POSTGRES_DB: "systemio"
        POSTGRES_USER: "systemio"
        POSTGRES_PASSWORD: "123456"
      ports:
          - "5432:5432"
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U systemio -d systemio" ]
      volumes:
        - ./tmp/db:/var/lib/postgresql/data



###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
